apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job-1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-job
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Running backup job
          restartPolicy: OnFailure
