apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dag-diamond
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: diamond
    templates:
    - name: echo
      inputs:
        parameters:
        - name: message
      container:
        image: alpine:3.13
        command: [echo, "{{inputs.parameters.message}}"]
    - name: diamond
      dag:
        tasks:
        - name: A
          template: echo
          arguments:
            parameters: [{name: message, value: A}]
        - name: B
          dependencies: [A]
          template: echo
          arguments:
            parameters: [{name: message, value: B}]
        - name: C
          dependencies: [A]
          template: echo
          arguments:
            parameters: [{name: message, value: C}]
        - name: D
          dependencies: [B, C]
          template: echo
          arguments:
            parameters: [{name: message, value: D}]
